backend:
  name: git-gateway
  repo: Cosec07/SE_NGO-Website
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/assets/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "Projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "_posts/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "Fun"
    label: "Funs"
    folder: "_posts/fun"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumb", widget: "image" }

  - name: "Recent"
    label: "Recent Events"
    folder: "_posts/recent"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumb", widget: "image" }

  - name: "Upcoming"
    label: "Upcoming Events"
    folder: "_posts/upcoming"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumb", widget: "image" }

  - name: "RecentProject"
    label: "recentproject"
    folder: "_posts/recentproj"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Avenue", name: "avenue", widget: "string" }

  - name: "Testimonial"
    label: "testimonial"
    folder: "_posts/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Comment", name: "comment", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Designation", name: "designation", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }

  - name: "ProfessionalTeam"
    label: "ProfessionalTeams"
    folder: "_posts/professionalteam"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Designation", name: "designation", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Information", name: "information", widget: "string" }

  - name: "RecentPost"
    label: "RecentPosts"
    folder: "_posts/recentpost"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Information", name: "information", widget: "string" }

  - name: "Feature"
    label: "feature"
    folder: "_posts/feature"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options:
            [
              "projects",
              "fun",
              "professionalteam",
              "recent",
              "recentproj",
              "testimonials",
              "upcoming",
              "feature",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
